### ISSUE TITLE
Pass environment variables in docker run.sh

### ISSUE THREAD

**Issue by swgkg** [wso2-attic/dockerfiles#50]
We need to update the run.sh in docker files to pass the environment variables.As an example sleep,debug that need to be pass as a environment variable.
docker run -d -e SLEEP=10000 --name wso2am wso2am:1.10.0

[1]https://github.com/wso2/dockerfiles/blob/master/common/scripts/docker-run.sh#L153

**Comment by chamilad** [comment]
I agree. This should have been an obvious functionality.

**Comment by ravihansa3000** [comment]
@swgkg care to send a PR? :)
