### ISSUE TITLE
Build the container for RunAsAny user

### ISSUE THREAD

**Issue by gordillo-ramon** [wso2-attic/dockerfiles#51]
Hi.

Regarding kubernetes pod security policies, there are some papers regarding the use of anonymous users for running the containers.

https://github.com/kubernetes/kubernetes/tree/master/pkg/security/podsecuritypolicy/user/runasany.go

It will be very useful if dockerfiles can be run with any user. Is it only needed to move from /mnt to /tmp, or there are other concerns about this enhancement?

Thanks.

**Comment by gordillo-ramon** [comment]
I have tried just to change from /mnt to /tmp, and I am facing another issue. /mnt/<product_name> is set up in the container as a concrete user, but first thing the entrypoint does is to move it to /mnt/<ip>/<product_name>. This cannot be done with anyuser, for permission limitations.

Why it is needed this move?

**Comment by gordillo-ramon** [comment]
From my experience, these are the changes that should be done to allow running the container with "RunAsAny" security policy:

1.  Move paths from /mnt to /tmp
_puppet_modules_: 
several files, particularly 
`hieradata/dev/wso2/common.yaml`

2.  Do a “ln -s” instead of a “mv” for /mnt/<ip>/<product> in 
_dockerfiles_: 
`common/scripts/entrypoint.sh`

3.  - grant “a+w” to some configuration files that need to be modified at startup (ex. common/scripts/entrypoint.sh, manipulates with sed), and change permissions from 754 to 755, to allow entering in them to all users):

/repository/conf/axis2/axis2.xml

/repository/conf/security/secret-conf.properties

```
  # set file permissions for carbon_home
  ensure_resource('exec', "set_permissions_${carbon_home}", {
    path               => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    cwd                => $carbon_home,
    command            => 'chmod -R 755 ./',
    logoutput          => 'on_failure',
    timeout            => 0,
    refreshonly        => true,
    notify             => Exec['set_permissions_axis2']
  })

  # set file permissions for axis2.xml, sed needs also grant for temp file on folder
  ensure_resource('exec', "set_permissions_axis2_xml", {
    path               => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    cwd                => $carbon_home,
    command            => 'chmod -R 777 ./repository/conf/axis2',
    logoutput          => 'on_failure',
    timeout            => 0,
    refreshonly        => true,
    notify             => Exec['set_permissions_secret_conf_properties']
  })

  # set file permissions for secret-conf.properties
  ensure_resource('exec', "set_permissions_secret_conf_properties", {
    path               => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    cwd                => $carbon_home,
    onlyif             => "test ! -f ./repository/conf/security/secret-conf.properties",
    command            => 'chmod -R 777 ./repository/conf/security',
    logoutput          => 'on_failure',
    timeout            => 0,
    refreshonly        => true,
    notify             => Exec['set_permissions_wso2server']
  })

  # set file permissions for wso2server.sh
  ensure_resource('exec', "set_permissions_wso2server", {
    path               => '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
    cwd                => $carbon_home,
    command            => 'chmod -R 777 ./bin/wso2server.sh',
    logoutput          => 'on_failure',
    timeout            => 0,
    refreshonly        => true,
    notify             => Exec['remove_product_pack']
  })


```

_puppet_modules_: 
`modules/wso2base/manifests/install.pp`

**Comment by gordillo-ramon** [comment]
Seems there are lots of files affected by permissions, for example tmp, repository/logs, bundles patched, etc. So from my point of view, the only way is to move to a 777 permission for the entire product.

Any other alternative?

**Comment by gordillo-ramon** [comment]
We also need to set HOME variable, in case uid has no home.

**Comment by gordillo-ramon** [comment]
Mode 777 in modules/wso2base/manifests/patch.pp too.

**Comment by ravihansa3000** [comment]
"mv" was changed to "ln -s" in #54. That was a mistake. Should never have made it to master. Thanks for reporting @gordillo-ramon 

Regarding file permission issue, I don't see any reason to set 777. Not sure why it was done that way. @imesh @pubudu538 @anuruddhal any thoughts?

We set 'USER wso2user' directive in Dockerfile of each product so it doesn't have sudo privileges anyway. Puppet creates 'wso2user' and 'wso2group' at build time.

**Comment by imesh** [comment]
@ravihansa3000 Why do you say #54 was a mistake? I think what @gordillo-ramon says is that we need that functionality for "RunAsAny" requirement.

Technically I do not any reason to use 777 for a folder structure except for a set of executable files. Therefore I guess is an issue in puppet that we have applied chmod 777 for repository/conf/axis2 and repository/conf/security folders.

@gordillo-ramon Since we already create a new user called wso2user for executing the Carbon server inside the container, wouldn't this requirement be satisfied if we change it accordingly?

Thanks

**Comment by gordillo-ramon** [comment]
Hi.

The problem is that running as named user, it is "RunAsUser". Currently, it is the usual security context for pods in kubernetes. However, "RunAsAny" exists for some time in Openshift, and it seems this security context will be promoted to kubernetes (see https://github.com/kubernetes/kubernetes/blob/master/pkg/security/podsecuritypolicy/user/runasany.go)

With this security context, when a pod is instanced, a new random user (from a range) is created and the container runs with this "random UID". That leads to some trouble in terms of permissions, not only for axis2 folder but many others (for example, when patching the carbon kernel).

The ideal solution: review all file/folders that need this "any" write permission. Maybe, even if it can be a big task, review those writes will be a interesting task. 

- Are they needed at runtime or should be done at build time?
- Could a temporary folder, like /tmp, be used and deleted after the process?
- Is there any reason to keep some local resources (like h2 social databases), or should we move in a PaaS environment to have everything in their own pods?

**Comment by imesh** [comment]
@gordillo-ramon Thanks for the detailed explanation on "RunAsUser" feature! As I see running a server inside a container using a random user would be much similar to running it as wso2user. I do not see much difference. 

The wso2user is created at the container build time by disabling login [1] and no SSH services are run inside the container. Therefore the only way to get access to the container is to execute a docker exec command from the container host or by using a loophole in an application run on the server. If an intruder get access to the container host, that would compromise the containers anyway. The same may apply to deploying an application with an security vulnerability. Therefore I do not see any advantages of running a server with a random user over the current approach we have taken.

If you think its really necessary to proceed with "RunAsUser" approach, the permission issues can be resolved by extracting the distribution at the container startup inside the user home, using the random user.

[1] https://github.com/wso2/dockerfiles/blob/3a402342d97d544c42f71ea7bb5ef4b2b1ed1a1c/common/provision/default/image-config.sh#L26

**Comment by gordillo-ramon** [comment]
Hi, Imesh.

For your first comment, see (http://www.projectatomic.io/blog/2014/09/yet-another-reason-containers-don-t-contain-kernel-keyrings/), where it is explain that not everything in containers is namespaced, and that leads to sharing resources if two containers run with the same UID.

If I understand your approach, it will be needed not only extracting the distribution but all the steps that puppet is executing when building the images. Other than it seems not an approach for production to do all this stuff at start time, it will be almost same complex as reviewing the process.

Another reason to support this review is that one important feature con containers is their immutability. Ok, some of them has some properties that may be set up at start time, but no files should be added if possible. If not, big layers per container will be added to the storage of docker filesystem.

WDYT?

**Comment by imesh** [comment]
@gordillo-ramon Thanks for sharing the above link. As I see the UID sharing issue would only become a problem, if the software that runs inside the container uses the keyring or any other kernel features which are not namespaced. Currently AFAIK, WSO2 middleware does not use the keyring or kernel features. Therefore I do not think that would become an issue for us.

**Comment by gordillo-ramon** [comment]
Hi, Imesh. Are you 100% sure neither wso2 code nore any third-party libraries you are using (including jdk) uses this kind of features?

The previous link, just an example, was about kerberos cache. Maybe one wsois underlying library, for example is using that features. IMHO better safe than sorry.

**Comment by imesh** [comment]
@gordillo-ramon I agree! I will check this with all product teams and get back. Thanks!

**Comment by ravihansa3000** [comment]
@imesh I think my comment was misleading. #54 was NOT a mistake! On the contrary, we have fixed the mistake we have done in that PR.

I agree that we need to dig further into the issue raised by @gordillo-ramon and support RunAsAny user. Even if we confirm that no 3rd party lib or WSO2 code is using any kernel features that would make it a problem, there is no guarantee that any future version or new lib won't use such features.
