### ISSUE TITLE
Support for JDK8 and add JDK version a build parameter

### ISSUE THREAD

**Issue by dannykruitbosch** [wso2-attic/dockerfiles#59]
Hi,

Since most (I've checked them all) WSO2 product support Oracle JDK8 as well, it would be nice if we can use that in the docker images. And also add the jdk version as a parameter to the build scripts.

Thanks,

Danny

**Comment by imesh** [comment]
Thanks Danny for bringing this up! 
We already have support for specifying JDK version in Puppet based provisioning [1]. However it's still not there in default provisioning scheme [2]. We definitely need to add this. If you are willing to contribute, please feel free to send a PR. Thanks!

[1] https://github.com/wso2/puppet-modules/blob/master/hieradata/dev/common.yaml#L16
[2] https://github.com/wso2/dockerfiles/blob/master/common/provision/default/image-prep.sh#L24
