### ISSUE TITLE
Unable to build profile images of wso2am latest version (2.0.0)

### ISSUE THREAD

**Issue by memorais** [wso2-attic/dockerfiles#65]
I'm trying to build separated profiles to wso2am latest version (2.0.0) but it only creates the default one. If I use version 1.10.0 it works well. Am I missing something or it just don't work with wso2am latest version?

**Comment by chamilad** [comment]
@memorais Are you using Puppet to configure the Docker images? If so which version are you using? Make sure Puppet has the related Hieradata and the templates matching the product version you need to build.

**Comment by memorais** [comment]
@chamilad No, I'm not using puppet. I'm just putting the files in common/provision/default/files directory and using the build.sh script.

**Comment by imesh** [comment]
Profile images cannot be built with default provisioning scheme, would need to use Puppet. Please see the documentation for more information:
https://docs.wso2.com/display/DF120/WSO2+Dockerfiles+Documentation
