### ISSUE TITLE
Editing configuration file

### ISSUE THREAD

**Issue by vcupelloni** [wso2-attic/dockerfiles#68]
Hi, 
following this doc https://docs.wso2.com/display/MB300/Integrating+WSO2+ESB I need to edit configuration file that are stored inside the container. 
There is no vi or nano installed by default and it seems that I cannot install software when, after ./run.sh, I'm connected to the container...
Am I missing something?

**Comment by imesh** [comment]
A configuration cannot be changed without rebuilding the docker image. The reason is that to apply a configuration change the server needs to be restarted. However, if a server that runs inside a container is restarted, the container will get terminated.

**Comment by vcupelloni** [comment]
So, I have to edit configuration file in the .zip archive put in <DOCKERFILES_HOME>/common/provision/default/files and then run build.sh to rebuild the image?

**Comment by pubudu538** [comment]
What you suggested is also possible. But we recommend puppet based provisioning. You can use puppet to manage your configurations. https://docs.wso2.com/display/DF120/Building+Docker+Images
