### ISSUE TITLE
validateDockerVersion() returns a false value for docker latest edition - v17.03.0-ce

### ISSUE THREAD

**Issue by rumeshbandara** [wso2-attic/dockerfiles#69]
Since Docker is on a monthly release cycle and uses a new `YY.MM` versioning scheme, current `validateDockerVersion()` function in `docker-build.sh`, not detecting the latest version format.

New format - `v17.03.0-ce`
Old format - `v1.13.1`

**Comment by imesh** [comment]
Thanks Rumesh for reporting this! We will check this and get back to you soon!

**Comment by javierjeronimo** [comment]
Any update? Thank you.

**Comment by rumeshbandara** [comment]
It has fixed here - https://github.com/wso2/docker-common/commit/30bc28930a9e401503c275278e9c1c5d35ff4aff#diff-268efe2a5282875548af904d51a8577d
