### ISSUE TITLE
WSO2 IS is now 5.3.0, and WUM worth to be included

### ISSUE THREAD

**Issue by astesin** [wso2-attic/dockerfiles#71]
Hi,
thanks for a great job! Just a few minor notes:

1. WSO2 Identity Server is now 5.3.0,
2. for it, JDK8 is recommended, AFAIK,
3. and there is a valuable command line utility already around - WSO2 Update Manager (WUM) which I think worth to be included in the image, so one will be able to create derivative images with patches and bugfixes applied.

Thank you for your kind attention!
WBR,
Andrii

**Comment by imesh** [comment]
Hi Andrii,

Thanks for your valuable feedback!! We are now in the process of splitting this repository into product specific repositories. Would you mind reporting this under WSO2 IS Dockerfile [1] repository?

[1] https://github.com/wso2/docker-is

Thanks
Imesh
