### ISSUE TITLE
Issue in running docker on windows environment

### ISSUE THREAD

**Issue by nadeesha5814** [wso2-attic/dockerfiles#72]
I am trying to sun pattern 1 on a windows environment using docker terminal for windows and the following issues comes up

/usr/local/bin/init.sh: /mnt/172.18.0.2/wso2am-2.1.0/bin/wso2server.sh: /bin/sh^M: bad interpreter: No such file or directory

 Please look into this.

Thank you,
Nadeesha

**Comment by scara** [comment]
Hi Nadeesha,
you can't: _wso2base_ runs on Linux (`FROM ubuntu:latest`) so you need to run it on a Linux based kernel; you should look for _Docker __for__ Windows_, https://docs.docker.com/docker-for-windows/.

HTH,
Matteo

**Comment by nadeesha5814** [comment]
Hi Scara,
I am running this on Docker for Windows and encountered the issue.

Thank you,
Nadeesha

**Comment by imesh** [comment]
Matteo is correct, WSO2 docker images have not been designed to run on Docker for Windows yet. Might need to use a Linux machine for the moment.

**Comment by scara** [comment]
Hi @nadeesha5814,
please double check if you're running "on Windows" or "on Linux", https://docs.docker.com/docker-for-windows/#switch-between-windows-and-linux-containers.

HTH,
Matteo

**Comment by eliassal** [comment]
You can run linux images on windows by switching "Docker Desktop to Linux instead of windows
